version: 2

jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: 'cypress/browsers:node12.18.0-chrome83-ff77'
        environment:
          TERM: xterm
    parallelism: 10
    steps:
      - checkout
#      - run: pwd
      - run: ls
      - restore_cache:
          keys:
            - 'v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}'
            - 'v2-deps-{{ .Branch }}-'
            - v2-deps-
      - run: npm ci
      - save_cache:
          key: 'v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}'
          paths:
            - ~/.npm
            - ~/.cache
      - run:
          name: Running OT test1
          command: node_modules/.bin/cypress run  --spec "cypress/integration/OT/*" --browser chrome --headless
      - store_test_results:
          path: results
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots

